import turtle 
khodinky = turtle.Turtle()
turtle.Screen().bgcolor("black")
khodinky.color("white")
t = turtle.Turtle()
def hodinky():
	khodinky.seth(90)
	for i in range(12):
		khodinky.penup()
		khodinky.forward(170)
		khodinky.pendown()
		khodinky.forward(30)
		khodinky.teleport(0,0)
		khodinky.right(360/12)
	khodinky.hideturtle()
def rucicky(hodina,minuta):
	t.color("blue")
	t.width(4)
	t.seth(90)
	t.right(hodina*(360/12))
	t.forward(100)
	t.stamp()
	t.teleport(0,0)
	t.color("red")
	t.width(1)
	t.seth(90)
	t.right(minuta*(360/60))
	t.forward(200)
	t.stamp()
	t.hideturtle()
hodinky()
rucicky(12,00)
turtle.mainloop()