import turtle
import random as r
kmen = turtle.Turtle()
kmen1 = turtle.Turtle()
konar = turtle.Turtle()
konar.hideturtle()
kmen.color("brown")
kmen1.color("brown")
kmen.teleport(0,-300)
kmen1.teleport(0,-300)
def kkmen():
    kmen.begin_fill()
    kmen1.begin_fill()
    kmen.seth(0)
    kmen1.seth(180)
    kmen.forward(100)
    kmen1.forward(100)
    kmen.seth(180)
    kmen.circle(-50,98)
    kmen1.seth(0)
    kmen1.circle(50,98)
    kmen.seth(90)
    kmen1.seth(90)
    kmen.forward(200)
    kmen1.forward(200)
    kmen.seth(180)
    kmen.forward(50)
    kmen1.seth(0)
    kmen1.forward(50)
    kmen.end_fill()
    kmen1.end_fill()
    kmen.hideturtle()
    kmen1.hideturtle()
def konare():
    konar.speed(0)
    konar.color("brown")
    konar.teleport(-50,-43)
    while True:
        velkost = r.randint(1,3)
        konar.width(velkost)
        suradnica = int(konar.xcor())
        konar.seth(90)
        konar.left(r.randint(1,50))
        konar.forward(100)
        konar.left(r.randint(1,50))
        konar.forward(100)
        konar.left(r.randint(1,90))
        konar.forward(100)
        konar.dot(30,"pink")
        konar.dot(10,"yellow")
        konar.teleport(int(suradnica+3),-43)
        if konar.xcor() > 49:
            break
    konar.teleport(50,-43)
    while True:
        velkost = r.randint(1,3)
        konar.width(velkost)
        suradnica = int(konar.xcor())
        konar.seth(90)
        konar.right(r.randint(1,50))
        konar.forward(100)
        konar.right(r.randint(1,50))
        konar.forward(100)
        konar.right(r.randint(1,90))
        konar.forward(100)
        konar.dot(30,"pink")
        konar.dot(10,"yellow")
        konar.teleport(int(suradnica-3),-43)
        if konar.xcor() < -49:
            break
        
kkmen()
konare()
turtle.mainloop()